In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
dat=pd.read_csv("train.csv")
print(dat)


       number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                       4         88.944468             57.862692   
1                       5         92.729214             58.518416   
2                       4         88.944468             57.885242   
3                       4         88.944468             57.873967   
4                       4         88.944468             57.840143   
5                       4         88.944468             57.795044   
6                       4         88.944468             57.682296   
7                       4         76.517718             57.175142   
8                       4         76.517718             56.808817   
9                       4         76.517718             56.442492   
10                      4         76.517718             55.709843   
11                      5        111.273574             63.713457   
12                      5         92.729214             58.201829   
13                      5         

In [2]:
features=pd.DataFrame(dat,columns=dat.columns)
target=pd.DataFrame(dat.critical_temp,columns=['critical_temp'])
features

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                       4         88.944468             57.862692   
1                       5         92.729214             58.518416   
2                       4         88.944468             57.885242   
3                       4         88.944468             57.873967   
4                       4         88.944468             57.840143   
5                       4         88.944468             57.795044   
6                       4         88.944468             57.682296   
7                       4         76.517718             57.175142   
8                       4         76.517718             56.808817   
9                       4         76.517718             56.442492   
10                      4         76.517718             55.709843   
11                      5        111.273574             63.713457   
12                      5         92.729214             58.201829   
13                      5         92.729214             58.518416   
14                      5         92.729214             59.468178   
15                      5         92.729214             61.051113   
16                      5         69.171250             47.505319   
17                      4         88.944468             57.873967   
18                      4         76.517718             56.808817   
19                      4         76.517718             57.541467   
20                      4         76.517718             57.175142   
21                      4         76.517718             56.259330   
22                      4         76.517718             56.076168   
23                      4         76.517718             55.709843   
24                      4         76.517718             55.343518   
25                      4         76.517718             54.977193   
26                      4         76.517718             56.625655   
27                      4         64.632218             55.790060   
28                      4         97.481600            152.464120   
29                      4         97.481600            104.627000   
...                   ...               ...                   ...   
21233                   7         64.073395             68.994691   
21234                   7         64.073395             71.436707   
21235                   7         64.073395             71.374207   
21236                   7         64.073395             70.874211   
21237                   7         64.073395             70.249216   
21238                   7         64.073395             68.999225   
21239                   7         64.073395             68.624228   
21240                   2        138.715500            172.638000   
21241                   3        125.186800            129.705592   
21242                   3        125.186800            129.705592   
21243                   3        171.633667            149.186783   
21244                   3        171.633667            149.186783   
21245                   3        171.633667            149.186783   
21246                   5         70.406250             43.096221   
21247                   3        135.777533            135.467640   
21248                   3        135.777533            135.467640   
21249                   3        135.777533            135.467640   
21250                   3        135.539823            105.341263   
21251                   3        135.013667            105.248412   
21252                   3         86.607717             80.820500   
21253                   4         99.290200             85.845160   
21254                   4         99.290200             85.845160   
21255                   3         89.389833             89.389833   
21256                   3         89.389833             89.389833   
21257                   3         89.389833             89.389833   
21258                   4        106.957877             53.095769   
21259

In [3]:
cor=dat.corr()
#print(cor)
print(abs(cor['critical_temp']).sort_values())

gmean_fie                          0.025103
entropy_ThermalConductivity        0.085862
mean_fie                           0.102268
mean_atomic_radius                 0.105273
wtd_gmean_ElectronAffinity         0.107359
wtd_mean_ElectronAffinity          0.111516
mean_atomic_mass                   0.113523
std_Density                        0.115243
wtd_entropy_ThermalConductivity    0.116728
range_FusionHeat                   0.140714
range_Valence                      0.143546
gmean_atomic_radius                0.143770
wtd_range_ElectronAffinity         0.185348
mean_ElectronAffinity              0.193550
wtd_std_FusionHeat                 0.195571
std_FusionHeat                     0.201310
wtd_std_Density                    0.207663
std_Valence                        0.208072
gmean_atomic_mass                  0.230345
wtd_entropy_ElectronAffinity       0.237648
range_Density                      0.260536
std_ElectronAffinity               0.262103
range_ElectronAffinity          

In [4]:
# Separating out the features
X = dat.iloc[:, :81]
# Seprating out the target
y = dat.iloc[:,81:]
X.head()


number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   4         88.944468             57.862692   
1                   5         92.729214             58.518416   
2                   4         88.944468             57.885242   
3                   4         88.944468             57.873967   
4                   4         88.944468             57.840143   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          66.361592              36.116612             1.181795   
1          73.132787              36.396602             1.449309   
2          66.361592              36.122509             1.181795   
3          66.361592              36.119560             1.181795   
4          66.361592              36.110716             1.181795   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.062396          122.90607              31.794921   
1                 1.057755          122.90607              36.161939   
2                 0.975980          122.90607              35.741099   
3                 1.022291          122.90607              33.768010   
4                 1.129224          122.90607              27.848743   

   std_atomic_mass       ...         mean_Valence  wtd_mean_Valence  \
0        51.968828       ...                 2.25          2.257143   
1        47.094633       ...                 2.00          2.257143   
2        51.968828       ...                 2.25          2.271429   
3        51.968828       ...                 2.25          2.264286   
4        51.968828       ...                 2.25          2.242857   

   gmean_Valence  wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  \
0       2.213364           2.219783         1.368922             1.066221   
1       1.888175           2.210679         1.557113             1.047221   
2       2.213364           2.232679         1.368922             1.029175   
3       2.213364           2.226222         1.368922             1.048834   
4       2.213364           2.206963         1.368922             1.096052   

   range_Valence  wtd_range_Valence  std_Valence  wtd_std_Valence  
0              1           1.085714     0.433013         0.437059  
1              2           1.128571     0.632456         0.468606  
2              1           1.114286     0.433013         0.444697  
3              1           1.100000     0.433013         0.440952  
4              1           1.057143     0.433013         0.428809  

[5 rows x 81 columns]

In [5]:
y.head()

critical_temp
0           29.0
1           26.0
2           19.0
3           22.0
4           23.0

In [6]:
y.tail()

critical_temp
21258           2.44
21259         122.10
21260           1.98
21261           1.84
21262          12.80

In [7]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)
X

C:\Users\rahul\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\rahul\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


array([[-0.0800575 ,  0.04673292, -0.45165095, ..., -0.40616628,
        -0.83837245, -0.52006971],
       [ 0.6147436 ,  0.17426938, -0.43207104, ..., -0.36235194,
        -0.42686578, -0.45082134],
       [-0.0800575 ,  0.04673292, -0.45097762, ..., -0.37695672,
        -0.83837245, -0.50330427],
       ...,
       [-1.46965972,  0.40792698,  0.67545689, ...,  1.75534096,
        -0.7001588 , -0.60141582],
       [-1.46965972,  0.40792698,  0.71984372, ...,  0.7432298 ,
        -0.7001588 , -0.46423977],
       [-0.77485861, -0.0030091 ,  0.41416385, ...,  0.32407265,
         1.18612097,  1.81314381]])

In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components=14)
principalComponents = pca.fit_transform(X)
principalComponents


array([[-3.66448679,  0.99164271,  3.0452597 , ...,  0.15100241,
        -0.52117502, -0.01901598],
       [-4.55546842, -0.21458477,  1.7228725 , ...,  0.56539336,
        -0.60543861, -0.01078517],
       [-3.48817626,  1.05516727,  3.13082075, ...,  0.1431654 ,
        -0.56608573, -0.01985135],
       ...,
       [10.47746178, -0.93194296,  1.57264039, ..., -0.93978605,
         0.55783681, -0.90346512],
       [ 9.77188538, -1.001345  ,  1.21560166, ..., -0.58691712,
         0.76475518, -1.05926468],
       [ 3.91560139,  1.44638503, -1.91616717, ..., -0.56521871,
        -0.08050486,  1.70197654]])

In [9]:
#pca.explained_variance_ratio_.cumsum()
pca.explained_variance_ratio_

array([0.38931798, 0.10482209, 0.095212  , 0.0790773 , 0.05882183,
       0.03788369, 0.03622251, 0.03107107, 0.02361113, 0.0197788 ,
       0.01828367, 0.01458597, 0.01178446, 0.00998554])

In [10]:
pca.explained_variance_ratio_.cumsum()


array([0.38931798, 0.49414007, 0.58935207, 0.66842937, 0.7272512 ,
       0.76513489, 0.8013574 , 0.83242847, 0.8560396 , 0.87581839,
       0.89410206, 0.90868803, 0.9204725 , 0.93045804])

In [11]:
from sklearn.model_selection import train_test_split
#Train and Test splitting of data 
X_train, X_test, y_train, y_test = train_test_split(principalComponents, y, test_size = 0.20, random_state = 21)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((17010, 14), (4253, 14), (17010, 1), (4253, 1))

In [12]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score

DT = DecisionTreeRegressor (max_depth=11)
# Your code here
# DTClassifier.fit (# Your code here, # Your code here)
#Hint: 
#DT.fit (X_test, y_test)  
DT.fit(X_train,y_train)
#DT.fit(principalComponents,y)

DecisionTreeRegressor(criterion='mse', max_depth=11, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [13]:
#predicted_labels = DT.predict(X_test)
#predicted_labels = DT.predict(principalComponents)
predicted_labels = DT.predict(X_train)
predicted_labels

array([19.36804113,  2.06714286, 18.54070248, ..., 74.30704225,
        8.87777778,  3.8590625 ])

In [14]:
predicted_labels.shape

(17010,)

In [15]:
predicted_labels1 = DT.predict(X_test)
predicted_labels1

array([59.79375   , 59.79375   , 21.78319428, ..., 10.33384615,
       83.84901961, 64.63684211])

In [16]:
predicted_labels1.shape

(4253,)

In [17]:
from sklearn.metrics import mean_squared_error
from math import sqrt

#rms = sqrt(mean_squared_error(y_test, predicted_labels))
#rms = sqrt(mean_squared_error(y, predicted_labels))
rms = sqrt(mean_squared_error(y_train, predicted_labels))
rms2 = sqrt(mean_squared_error(y_test, predicted_labels1))

print(rms)
rms2

10.00762828403335


13.827095412245757

In [18]:
DT.score(X_train,y_train)


0.9147288553081225

In [19]:
DT.score(X_test,y_test)


0.8363206457508447