In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
dat=pd.read_csv("train.csv")
print(dat)


       number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                       4         88.944468             57.862692   
1                       5         92.729214             58.518416   
2                       4         88.944468             57.885242   
3                       4         88.944468             57.873967   
4                       4         88.944468             57.840143   
5                       4         88.944468             57.795044   
6                       4         88.944468             57.682296   
7                       4         76.517718             57.175142   
8                       4         76.517718             56.808817   
9                       4         76.517718             56.442492   
10                      4         76.517718             55.709843   
11                      5        111.273574             63.713457   
12                      5         92.729214             58.201829   
13                      5         

In [2]:
X=dat.iloc[:,:81]
y=dat.iloc[:,81:]
X.head()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   4         88.944468             57.862692   
1                   5         92.729214             58.518416   
2                   4         88.944468             57.885242   
3                   4         88.944468             57.873967   
4                   4         88.944468             57.840143   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          66.361592              36.116612             1.181795   
1          73.132787              36.396602             1.449309   
2          66.361592              36.122509             1.181795   
3          66.361592              36.119560             1.181795   
4          66.361592              36.110716             1.181795   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.062396          122.90607              31.794921   
1                 1.057755          122.90607              36.161939   
2                 0.975980          122.90607              35.741099   
3                 1.022291          122.90607              33.768010   
4                 1.129224          122.90607              27.848743   

   std_atomic_mass       ...         mean_Valence  wtd_mean_Valence  \
0        51.968828       ...                 2.25          2.257143   
1        47.094633       ...                 2.00          2.257143   
2        51.968828       ...                 2.25          2.271429   
3        51.968828       ...                 2.25          2.264286   
4        51.968828       ...                 2.25          2.242857   

   gmean_Valence  wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  \
0       2.213364           2.219783         1.368922             1.066221   
1       1.888175           2.210679         1.557113             1.047221   
2       2.213364           2.232679         1.368922             1.029175   
3       2.213364           2.226222         1.368922             1.048834   
4       2.213364           2.206963         1.368922             1.096052   

   range_Valence  wtd_range_Valence  std_Valence  wtd_std_Valence  
0              1           1.085714     0.433013         0.437059  
1              2           1.128571     0.632456         0.468606  
2              1           1.114286     0.433013         0.444697  
3              1           1.100000     0.433013         0.440952  
4              1           1.057143     0.433013         0.428809  

[5 rows x 81 columns]

In [3]:
y.head()

critical_temp
0           29.0
1           26.0
2           19.0
3           22.0
4           23.0

In [4]:
y.tail()

critical_temp
21258           2.44
21259         122.10
21260           1.98
21261           1.84
21262          12.80

In [5]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)
X

C:\Users\Mithun\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Mithun\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


array([[-0.0800575 ,  0.04673292, -0.45165095, ..., -0.40616628,
        -0.83837245, -0.52006971],
       [ 0.6147436 ,  0.17426938, -0.43207104, ..., -0.36235194,
        -0.42686578, -0.45082134],
       [-0.0800575 ,  0.04673292, -0.45097762, ..., -0.37695672,
        -0.83837245, -0.50330427],
       ...,
       [-1.46965972,  0.40792698,  0.67545689, ...,  1.75534096,
        -0.7001588 , -0.60141582],
       [-1.46965972,  0.40792698,  0.71984372, ...,  0.7432298 ,
        -0.7001588 , -0.46423977],
       [-0.77485861, -0.0030091 ,  0.41416385, ...,  0.32407265,
         1.18612097,  1.81314381]])

In [56]:
from sklearn.decomposition import PCA
pca = PCA(n_components=50)
principalComponents = pca.fit_transform(X)
principalComponents


array([[-3.66448679e+00,  9.91642689e-01,  3.04525969e+00, ...,
         4.03224143e-02, -3.91465530e-02,  3.14046797e-02],
       [-4.55546842e+00, -2.14584743e-01,  1.72287252e+00, ...,
         4.26215456e-02,  1.41138211e-01,  2.55563111e-01],
       [-3.48817626e+00,  1.05516726e+00,  3.13082075e+00, ...,
         4.32381827e-02, -5.81878044e-02,  1.69116484e-02],
       ...,
       [ 1.04774618e+01, -9.31942974e-01,  1.57264038e+00, ...,
         4.87628484e-02,  2.81228932e-02, -3.38161203e-02],
       [ 9.77188538e+00, -1.00134503e+00,  1.21560162e+00, ...,
         2.42513758e-02, -6.15077197e-03,  1.03870618e-02],
       [ 3.91560139e+00,  1.44638502e+00, -1.91616716e+00, ...,
        -1.53957484e-01, -1.66542864e-02, -5.45741823e-02]])

In [57]:
#pca.explained_variance_ratio_.cumsum()
pca.explained_variance_ratio_

array([3.89317982e-01, 1.04822088e-01, 9.52120001e-02, 7.90773008e-02,
       5.88218289e-02, 3.78836850e-02, 3.62225141e-02, 3.10710704e-02,
       2.36111258e-02, 1.97787961e-02, 1.82836690e-02, 1.45859739e-02,
       1.17844636e-02, 9.98553996e-03, 9.82476180e-03, 7.81519491e-03,
       7.18792707e-03, 5.43466303e-03, 4.83327429e-03, 3.81676544e-03,
       3.02273402e-03, 2.86551931e-03, 2.56483087e-03, 2.07111321e-03,
       1.97217790e-03, 1.86288155e-03, 1.70037886e-03, 1.42592696e-03,
       1.26293775e-03, 1.15126820e-03, 1.02409524e-03, 9.60418058e-04,
       9.19262047e-04, 7.18768361e-04, 6.84926194e-04, 6.20909896e-04,
       5.70768972e-04, 4.92969119e-04, 4.36838342e-04, 4.22680904e-04,
       3.26131817e-04, 3.06014115e-04, 2.56982488e-04, 2.37422891e-04,
       2.23531100e-04, 2.15360536e-04, 1.96512986e-04, 1.87565390e-04,
       1.80759718e-04, 1.75223526e-04])

In [58]:
pca.explained_variance_ratio_.cumsum()


array([0.38931798, 0.49414007, 0.58935207, 0.66842937, 0.7272512 ,
       0.76513489, 0.8013574 , 0.83242847, 0.8560396 , 0.87581839,
       0.89410206, 0.90868803, 0.9204725 , 0.93045804, 0.9402828 ,
       0.94809799, 0.95528592, 0.96072059, 0.96555386, 0.96937062,
       0.97239336, 0.97525888, 0.97782371, 0.97989482, 0.981867  ,
       0.98372988, 0.98543026, 0.98685619, 0.98811913, 0.98927039,
       0.99029449, 0.99125491, 0.99217417, 0.99289294, 0.99357786,
       0.99419877, 0.99476954, 0.99526251, 0.99569935, 0.99612203,
       0.99644816, 0.99675418, 0.99701116, 0.99724858, 0.99747211,
       0.99768747, 0.99788399, 0.99807155, 0.99825231, 0.99842754])

In [59]:
from sklearn.model_selection import train_test_split
#Train and Test splitting of data 
X_train, X_test, y_train, y_test = train_test_split(principalComponents, y, test_size = 0.20, random_state = 21)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((17010, 50), (4253, 50), (17010, 1), (4253, 1))

In [69]:
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor

ytr=np.ravel(y_train)
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, ytr)
y_pred = regressor.predict(X_test)
y_pred

array([68.335     , 62.61      , 14.39058333, ..., 13.0005    ,
       79.59816667, 56.114     ])

In [70]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 5.732110741747617
Mean Squared Error: 105.78979477082439
Root Mean Squared Error: 10.285416606575758


In [71]:
regressor.score(X_train,ytr)

0.9756098371216535

In [72]:
regressor.score(X_test,y_test)

0.9094317954410346